services:
  server-blue:
    container_name: server-blue
    image: "${DOCKER_USERNAME}/autotrading:server-blue-${GITHUB_SHA}"
    build:
      context: .
      dockerfile: Dockerfile.server
    env_file: .env
    environment:
      TZ: "Asia/Seoul"
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - /log:/app/log
    networks:
      - web

  signal-blue:
    container_name: signal-blue
    image: "${DOCKER_USERNAME}/autotrading:signal-blue-${GITHUB_SHA}"
    build:
      context: .
      dockerfile: Dockerfile.signal
    environment:
      TZ: "Asia/Seoul"
    ports:
      - "3001:3000"
    expose:
      - "3001"
    volumes:
      - /log:/app/log
    networks:
      - web

networks:
  web:
    external: true
    name: web
