services:
  server-blue:
    container_name: server-green
    image: "autotrading"
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      TZ: "Asia/Seoul"
    ports:
      - "3001:3000"
    expose:
      - "3001"
    command: ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "3001"]
    volumes:
      - AutoTradingLog:/app/log
    healthcheck:
      test: >
        bash -c ': > /dev/tcp/localhost/3000' || exit 1
      interval: 30s
      timeout: 10s
      retries: 2

volumes:
  AutoTradingLog:
    external: true