
services:
  server-blue:
    container_name: server-blue
    image: "${DOCKER_USERNAME}/autotrading:server-blue-${GITHUB_SHA}"
    env_file: .env
    environment:
      TZ: "Asia/Seoul"
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - /log:/app/log
    networks:
      - web

  signal-blue:
    container_name: signal-blue
    image: "${DOCKER_USERNAME}/autotrading:signal-blue-${GITHUB_SHA}"
    environment:
      TZ: "Asia/Seoul"
    ports:
      - "3001:3000"
    expose:
      - "3001"
    volumes:
      - /log:/app/log
    networks:
      - web

  nginx:
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server-blue
      - signal-blue
    volumes:
      - /var/log/nginx:/var/log/nginx
    networks:
      - web

networks:
  web:
    external: true
    name: web
