name: blue green cd

on:
  push:
    branches:
      - main
jobs:
  SSH:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: ssh to compute engine
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd ~/cr/AutoTrading
            git pull https://github.com/consoleolog/AutoTrading.git
            sh deploy.sh