name: Blue/Green CD

on:
  push:
    branches: ["develop"]

  env:
    DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
    GITHUB_SHA: ${{github.sha}}

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Generate .env file
          run: |
            cd AutoTrading 
            echo "${{secrets.ENA_FILE}}" > .env 
            echo "DOCKER_USERNAME=${{secrets.DOCKER_USERNAME}}" >> .env
            echo "GITHUB_SHA=${{github.sha}}" >> .env

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_ACCESS_TOKEN}}

        - name: Build & Push Images
          run: |
            cd AutoTrading
            docker-compose -f docker-compose.blue-build.yaml build
            docker-compose -f docker-compose.green-build.yaml build
            docker-compose -f docker-compose.blue-build.yaml push
            docker-compose -f docker-compose.green-build.yaml push
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_ACCESS_TOKEN}}

      - name: Run Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            cd ~/cr/AutoTrading
            chmod +x deploy.sh
            mkdir test